app:
    resource: '@AppBundle/Controller/'
    type: annotation

my:
    resource: "@MyBundle/Controller/"
    type: annotation

test:
    resource: "@MyBundle/Controller/TestController.php"
    type: annotation
    prefix: /test

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin











